# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

logger: !include logger.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
homekit: !include homekit.yaml
modbus: !include modbus.yaml

input_boolean:
  homepod_temperature_update:
    name: "Триггер запроса температуры HomePod"
    initial: off

template:
  - trigger:
      - platform: webhook
        webhook_id: !secret homepod_temperature_webhook_id
        allowed_methods:
          - POST
        local_only: true
    sensor:
      - name: "HomePod Temperature"
        state: "{{ trigger.json.temperature }}"
        unit_of_measurement: "°C"
